server:
  port: 7001

spring:
  application:
    name: @artifactId@
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_HOST:pig-register}:${NACOS_PORT:8848}
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
  config:
    import:
      - nacos:application-${spring.profiles.active}.yml
      - nacos:${spring.application.name}-${spring.profiles.active}.yml
  profiles:
    active: @profiles.active@
  datasource:  # 示例数据源配置，注意修改
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://tickets-mysql:3306/tickets_demo?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai

# spring security 配置
security:
  oauth2:
    client:
      client-id: pig
      client-secret: pig
      scope: server

